- command:
   name: runtests
   execute:
      - cd tests/driver
      - ./test_runner
   description: Run Hunter unit tests
- command:
   name: debug
   execute:
      - gprbuild -P hunter.gpr
   description: Build Hunter in debug mode
- command:
   name: release
   execute:
      - others/build.tcl
   description: Build Hunter in release mode
- command:
   name: analyze
   execute:
      - gprbuild -P hunter.gpr -XMode=analyze
   description: Build Hunter in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P hunter.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P hunter.gpr
   description: Regenerate unit tests
- command:
   name: tests
   execute:
      - gprbuild -P tests/driver/test_driver.gpr
   description: Build Hunter unit tests
- command:
   name: docs
   execute:
      - others/generatedocs.tcl
   description: Generate code documentation
- command:
   name: gprof
   execute:
      - gprof bin/hunter gmon.out
   description: Generate gprof report
- command:
   name: buildall
   execute:
      - bob release
      - bob debug
   description: Build Hunter release then debug version
- command:
   name: generatetranslation
   execute:
      - others/translations.tcl generate
   description: (Re)Generate ROOT translation of the program
- command:
   name: createtranslation
   execute:
      - others/translations.tcl create $1
   description: Create a new translation for the selected language
- command:
   name: updatetranslations
   execute:
      - others/translations.tcl update
   description: Update all existing translations (except ROOT)
