language: shell

os: linux

branches:
   except:
      - travis-dev-build

services:
   - docker

install:
   - docker pull ghcr.io/thindil/tashy:8.6.9

script:
   - docker run -v $(pwd):/app ghcr.io/thindil/tashy:8.6.9 /bin/sh -c "apt-get update && apt-get install -y libmagic-dev libxmlada-schema9-dev libxmlada-input9-dev && cd /app && others/build.tcl"
   - tar -czf hunter-development.tar.gz usr

before_deploy:
  - git tag -f travis-dev-build
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh travis-dev-build
  - git remote remove gh

deploy:
  provider: releases
  token: $KEY
  skip_cleanup: true
  file: hunter-development.tar.gz
  name: Continuous Integration build
  release_notes: Development build of Hunter built by Travis CI.
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
   branch: tk
