#!/bin/sh

if [ -z ${XDG_DATA_DIRS+x} ]; then
   export XDG_DATA_DIRS=/usr/share:/usr/local/share
fi
cd $APPDIR/usr/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPDIR/usr/lib
export GDK_PIXBUF_MODULE_FILE=$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
export GDK_PIXBUF_MODULEDIR=$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/
export FONTCONFIG_FILE=$APPDIR/usr/etc/fonts/fonts.conf
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$APPDIR/usr/share
export GSETTINGS_BACKEND=memory
export RUNFROMSCRIPT=1
./hunter
