#!/usr/bin/env sh

directory=$(pwd)
if [ -z ${XDG_DATA_DIRS+x} ]; then
   export XDG_DATA_DIRS=/usr/share:/usr/local/share
fi
if [ -z ${APPDIR+x} ]; then
   export APPDIR="$directory"
fi
cd $APPDIR/usr/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPDIR/usr/lib
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$APPDIR/usr/share
if [ "$#" -ne 0 ]
then
   if [ "${1%${1#?}}"x = "/x" ]
   then
      ./hunter "$1"
   else
      ./hunter "$directory/$1"
   fi
else
   ./hunter
fi
