name: AdaControl checks - console version

on:
  push:
    branches: [ tk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adacontrol:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run AdaControl
      run: |
         mkdir obj
         cd obj
         adactl -f ../others/rules.aru -p ../others/console.gpr -o ../adacontrol.log -r hunter-tcl-cargv-chelper-unicode-sax-dom-input_sources-terminal_interface
         cd ..

    - name: Upload the log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
         name: adacontrol.log
         path: adacontrol.log

