name: AdaControl checks

on:
  push:
    branches: [ tk ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run AdaControl
      run: |
         mkdir obj
         cd obj
         adactl -f ../others/rules.aru -p ../hunter.gpr -o ../adacontrol.log -r hunter-tcl-cargv-unicode-sax-dom-input_sources
         cd ..

    - name: Upload the log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
         name: adacontrol.log
         path: adacontrol.log

